# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  # If you don't need these, delete them.
  # If you do, give each its own URL env var or let them reuse DATABASE_URL.
  # cache:
  #   <<: *primary_production
  #   url: <%= ENV.fetch("CACHE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
  #   migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>
    # Only keep migrations_paths if you actually have these dirs/files
    # migrations_paths: db/cable_migrate