# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>

  cable:
    <<: *primary_production
    url: <%= ENV.fetch("CABLE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>

  queue:
    <<: *primary_production
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", ENV.fetch("DATABASE_URL")) %>